# 1、异常

- 异常就是程序运行时发生错误的信号
- 常见异常
  - `AttributeError`     试图访问一个对象没有的属性		
  - `IOError`    输入/输出异常，基本上是无法打开文件		
  - `ImportError`    无法引入模块或包，基本上是路径问题或名称错误		
  - `IndentationError`    语法错误，代码没有正确对齐		
  - `IndexError`    下标索引超出序列边界		
  - `KeyError`    试图访问字典中不存在的键		
  - `KeyboardInterrupt`    Ctrl+C被按下		
  - `NameError`    使用一个未被赋予对象的变量		
  - `SyntaxError`    代码非法		
  - `TypeError`    传入对象类型与要求的不符合		
  - `UnboundLocalError`    试图访问一个还未被设置的局部变量，基本上是因为有一个同名的全局变量		
  - `ValueError`    传入一个调用者不期望的值  

# 2、异常处理

- 即程序员编写特定的代码，专门来捕捉异常，如果捕捉成功则进入另一个处理分支，执行程序员为其定制的逻辑，使程序不会崩溃，就是一次处理

- 为什么要进行异常处理		

  - python检测到错误时，触发异常，在异常触发且未被处理的情况下，程序就在当前异常处终止

- 异常处理方法

  ```python
  try:
      pass             # 未出异常时运行的代码
  except [异常类型]:    # 异常类型不写时，则可以处理所有类型异常（该方法不能得知异常类型）
      pass	           # 出了异常后程序运行的代码
  except [异常类型]:    # 可以使用多分支处理异常（执行最上面的异常处理，然后退出分支）
      pass
  except [异常类型1, 异常类型2, ...]:  # 多分支合并
      pass
  ```

- 万能异常处理

  ```python
  try:
      pass
  except Exception as e:
      print(e)     # 打印异常的内容
      print(e.__traceback__.tb_lineno)   # 打印异常的行数
      pass
  ```

  - 万能异常应该放在所有异常最下面

# 3、其它异常处理

- else分支

  ```python
  try:
      pass
  except:
      pass
  else:        # 当try中的内容没有触发异常时，程序运行else代码
      pass
  ```

- finally分支

  ```python
  try:
      pass
  except:
      pass
  else:        # 当try中的内容没有触发异常时，程序运行else代码
      pass
  finally:     # finally中的代码无论如何都会执行，如用于关闭文件
      pass
  ```

  - 注意：
    - 即使在函数中，finally写在return后面，也会先执行finally代码			
    -  即便出现异常，也会先执行finally代码			 
    - finally用来回收一些操作系统的资源，如数据库连接 文件句柄打开等等

- 主动抛出异常`raise [异常类型]('给用户的提示')`

  - 如` raise ValueError("输入值不对")`

- 断言（语法）		

  - `assert [bool]`，如果`bool==True`，就继续执行代码，如果为False，则抛出异常，相当于

    ```
    if bool:
        pass
    else:
        raise [异常类型]
    ```

    





